### PR TITLE
update: signing

### PR DESCRIPTION
**Pull request by 2hyunbin**
@traderben HyperLiquid's signing method has been changed. TypeScript sdk is not being managed for a long time. Signing files written in the old way are no longer working. Therefore, it has been modified to work with new versions.

### CODE REVIEW

**Comment by traderben** [comment]
The existing code is up to date and is not the old way. The frontend constructs signatures with this exact code. You can add the extra code to make constructing an order action easier to do, but there's no need to change the way the signing code

**Review by traderben — CHANGES_REQUESTED** [review]
Also please don't change the naming convention. We prefer .tsx extensions for all files

**Comment by 2hyunbin** [comment]
@traderben Thank you for the feedback, I modified the PR to match the naming convention.

Since there has been an issue about the signing before, I think PR will be meaningful to TS users even if the previous signing works well(https://github.com/hyperliquid-dex/ts-examples/issues/1)

**Comment by traderben** [comment]
> @traderben Thank you for the feedback, I modified the PR to match the naming convention.
> 
> Since there has been an issue about the signing before, I think PR will be meaningful to TS users even if the previous signing works well(#1)

As mentioned in that issue, there was no problem with the signing code itself. I do not have time to review such a large PR and I also think the description may confuse future users that look at this repository. If you update the PR to not move code to different files unnecessarily and not change the actual signing code it should be much easier for me to review

**Pull request closed without merging**
